### ISSUE TITLE
Přesun podkategorie na první úroveň stromu.

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Catalog#19]
Přes admin nejde přesun podkategorii na první úroveň stromu.
Pro přesouvání ve stromu se v adminu používá input s nápovědou kam se má zadat nadřazená složka, ale samotné lomítko "/" tam dát nejde.

![recording_2017-01-31_094700](https://cloud.githubusercontent.com/assets/143115/22457948/8717a948-e79a-11e6-82fd-36e792a3bc55.gif)

**Comment by yarri** [comment]
Fixed in ae1c6f7. Sorry for the small delay! :)
