### ISSUE TITLE
Pamatovat si řazení v seznamu produktu v adminu

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Catalog#21]
Bylo by uživatelsky velice přívětivé, kdyby si administrace pamatovala řazení - např. v seznamu produktů. Když přidáváš produkty, chceš je mít řazené primárně podle data vložení nebo poslední úpravy. Systém si toto nastavení ale nepamatuje, takže to musíš dělat pokaždé znova.

![recording_2017-01-31_100412](https://cloud.githubusercontent.com/assets/143115/22458454/e31266e6-e79c-11e6-91ed-7ba3b2b655cc.gif)

**Comment by yarri** [comment]
Žádný obecný mechanismus pro ukládání třídění v adminech jsme doposud v našich projektech nevyvinuli. Nicméně alespoň v commitu 8aacf82e9b7af08b9187a9cc3c790fbca77d5adc bylo v adminu produktů nastaveno výchozí třídění dle datumu vytvoření.

**Comment by yarri** [comment]
Tím pádem bych to zavřel :)
