### ISSUE TITLE
Rename/split 'views/shared/_login.tpl' partial shared template

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Catalog#31]
File contains hole nabar, not only login form as one can expected from file name.
https://github.com/atk14/Atk14Catalog/blob/2e1c6dc296f20e5b72593f95543eba7289ee55c1/app/views/shared/_login.tpl#L1-L41

**Comment by yarri** [comment]
The template views/shared/_login.tpl was moved to views/shared/layout/_header.tpl in 13a5b92f49bf63d13ffed167f0740d0e62494ad6

Thank you mattez for the tip! :)
