### ISSUE TITLE
Sorting product list in catalog/detail

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Catalog#32]
Použitý `$cards_finder->getRecords()` ignoruje pořadí zadané přes admin.
Můj hotfix: zde naradit  `$cards_finder->getRecords()`

https://github.com/atk14/Atk14Catalog/blob/7ba1fc23f5069cbed6281f3d6001f63a764827df/app/views/categories/detail.tpl#L39-L41

za `cards=$category->getCards()`, které je použité v adminu, viz

https://github.com/atk14/Atk14Catalog/blob/7ba1fc23f5069cbed6281f3d6001f63a764827df/app/views/admin/categories/edit.tpl#L123

**Comment by yarri** [comment]
Toto bylo opraveno v commitu 98e956ce2c615084d4e5f3bf9494c1146f724d3d ve větvi develop.
